// <auto-generated />
namespace DispensaryTrack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AllTable_PkFkAddedV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AllTable_PkFkAddedV1));
        
        string IMigrationMetadata.Id
        {
            get { return "202303141952512_AllTable_PkFkAdded-V1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
