// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TokenDBV11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TokenDBV11));
        
        string IMigrationMetadata.Id
        {
            get { return "202305020913426_TokenDB-V1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
