// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EmployeeTable_PKEmail_UpdatedV20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmployeeTable_PKEmail_UpdatedV20));
        
        string IMigrationMetadata.Id
        {
            get { return "202305021004430_EmployeeTable_PK-Email_Updated-V-2.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
