// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StockTableAddedV30 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StockTableAddedV30));
        
        string IMigrationMetadata.Id
        {
            get { return "202305151946472_StockTableAdded-V-3.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
