// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MedicinePurchaseDistributor_TableRelationshipFixedV22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MedicinePurchaseDistributor_TableRelationshipFixedV22));
        
        string IMigrationMetadata.Id
        {
            get { return "202305082145077_MedicinePurchaseDistributor_TableRelationshipFixed-V2.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
