// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StockTablePurchaseTable_PkFkFixed_1to1V34 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StockTablePurchaseTable_PkFkFixed_1to1V34));
        
        string IMigrationMetadata.Id
        {
            get { return "202305160205046_StockTablePurchaseTable_PkFkFixed_1to1-V3.4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
